### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by bingalls** [sebastiandittrich/apollo-adonis#1]
@sebastiandittrich 
README.md needs to be updated with system requirements & required libraries. Here's how far I got.
Note that your package.json still uses the preview version of Adonis 5.
I run Mac OSX v10.15 Catalina with node v14 (node >= 13 may be needed for module support)
* `npm uninstall -g adonis-cli`
Create a _Server API_ project, following the instructions at https://preview.adonisjs.com/guides/quick-start Note that the main Adonis site is still at v4; steps have changed for v5. Install the following libraries (be sure to add `--save` to README)

`npm install --save`  #for each of the following
* apollo
* apollo-adonis
* apollo-server
* apollo-server-adonis
* apollo-server-express
* gql

Syntax for `start/apollo.ts` failed for me. I removed **gql** and replaced
```typescript
import ApolloServer from '@ioc:Apollo/Server'
```
with
```typescript
const { ApolloServer } = require('apollo-server-express')
```
Running `node ace serve --watch` I get an error
```javascript
TypeError: Cannot read property 'use' of undefined

at /Users/bruceingalls/code/apollo-adonis/start/routes.ts(anonymous):27
22  Route.get('/', async () => {
23    return { hello: 'world' }
24  })
25
26  import ApolloServer from './apollo'
27  ApolloServer.applyMiddleware(Route)
```
This is as far as I could get.

**Comment by sebastiandittrich** [comment]
Hey, thanks for opening this issue!

I know it's a bit late, but I have changed the API, updated the docs and made the dependencies more clear. If you still need the package, feel free to try out Version 1.0.0 and leave some Feedback here.
